package org.example.presentation;

public enum ScreenResult {
    EXIT,
    STARTUP,
    ADMIN_LOGIN,
    STUDENT_LOGIN,
    ADMIN_MENU,
    COURSE_MENU,
    COURSE_EDIT_MENU,
    COURSE_SORT_MENU,
    STUDENT_MANAGEMENT_MENU,
    STUDENT_EDIT_MENU,
    STUDENT_SORT_MENU,
    ENROLLMENT_MENU,
    STATISTICS_MENU,
    STUDENT_MENU,
    STUDENT_COURSE_MENU,
    STUDENT_REGISTER_COURSE_MENU,
    STUDENT_REGISTERED_COURSE_MENU,
    STUDENT_CANCEL_REGISTRATION_MENU,
    STUDENT_PASSWORD_MENU
}
